# NOTE: Generated By HttpRunner v3.1.4
# FROM: queryBusOppDetail.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseQuerybusoppdetail(HttpRunner):

    config = Config("testcase description")

    teststeps = [
        Step(
            RunRequest("/proprietor-zo-restful/bizopp/queryBusOppDetail")
            .post(
                "https://qtoread.ziroom.com/proprietor-zo-restful/bizopp/queryBusOppDetail"
            )
            .with_headers(
                **{
                    "Client-Version": "50901",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Request-Id": "aba1ebca:20210125151955",
                    "Sys": "app",
                    "User-Agent": "okhttp/3.12.6",
                    "appId": "8000004134",
                    "appType": "2",
                    "appVersion": "50901",
                    "imei": "47f244f0-edb2-47b7-a075-b4dc4edabeaa",
                    "needToken": "false",
                    "osType": "android",
                    "osVersion": "10",
                    "phoneName": "PCAM00",
                    "timeStamp": "1611559195728",
                    "token": "NjAwMDI5MzMtMi0wNkRFRUM0NDdBODBEMjNCQkVEQTU5RUFCMzFDQjg3Qy0xNjEyMTYzOTA0MTc1LTE=",
                }
            )
            .with_data(
                "a323c0f9221cf35037eb6f98ad765e15371f2bcd4f572b4fbf271fcdd25316162a655d2ddc9cdbb4476208d23cea58963b78d49ab1d724cb95dcffb85b1db6d6bcff658c5d418665b9cb950aaf796b55ff89080f8e0cce8313a47a7d1c35bd6c"
            )
            .validate()
            .assert_equal("status_code", 200)
            # .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
        ),
    ]


if __name__ == "__main__":
    TestCaseQuerybusoppdetail().test_start()
